#!/usr/bin/python
print("started")
import urllib2
from bs4 import BeautifulSoup
url = "https://www.wikipedia.org"
page = urllib2.urlopen(url)
soup = BeautifulSoup(page,"html.parser")
print(soup.title)
